[project]
name = "mvlite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "modal>=0.74.3",
    "ruff>=0.11.2",
    "usearch>=2.16.9",
]
